/*AUTO (SEED /INCREMENT) CONCEPT*/

CREATE TABLE CUSTOMER_DETAILS (
    CUSTID INT IDENTITY,
    CUSTNAME CHAR(10),
    PRODUCT_NAME CHAR(10),
    PRICE FLOAT
);

INSERT INTO CUSTOMER_DETAILS VALUES('SMITH', 'RICEBAG', 1000)
INSERT INTO CUSTOMER_DETAILS VALUES('TINA', 'OIL', 2000)
INSERT INTO CUSTOMER_DETAILS VALUES('PETER', 'SUGAR', 3000)
INSERT INTO CUSTOMER_DETAILS VALUES('STEVE', 'VIMA', 1000)


SELECT * FROM CUSTOMER_DETAILS
/*DELETE ENTIRE TABLE*/
DROP TABLE CUSTOMER_DETAILS

/*custid start with 21*/
CREATE TABLE CUSTOMER_DETAILS (
    CUSTID INT IDENTITY(21,1),
    CUSTNAME CHAR(10),
    PRODUCT_NAME CHAR(10),
    PRICE FLOAT
);
INSERT INTO CUSTOMER_DETAILS VALUES('SMITH', 'RICEBAG', 1000)
INSERT INTO CUSTOMER_DETAILS VALUES('TINA', 'OIL', 2000)
INSERT INTO CUSTOMER_DETAILS VALUES('TOM', 'SUGAR', 4000)
INSERT INTO CUSTOMER_DETAILS VALUES('STEVE', 'VIMA', 1000)


SELECT * FROM CUSTOMER_DETAILS