/*DQL*/

USE VTCLASS1

/*PROJECTION METHOD*/
SELECT * FROM CUSTOMER_DETAILS

/*SELECTION METHOD*/
SELECT CUSTNAME,PRICE FROM CUSTOMER_DETAILS

/*JOINS*/
CREATE TABLE COLLEGE_DATA(STDID INT,STUDNAME CHAR(10),STDAGE TINYINT)
CREATE TABLE WORKING_DATA(EMPID INT,EMPNAME CHAR(10),EMPAGE TINYINT)

SELECT * FROM COLLEGE_DATA
SELECT * FROM WORKING_DATA

INSERT INTO COLLEGE_DATA VALUES(1,'JOHN',22)
INSERT INTO COLLEGE_DATA VALUES(2,'SMITH',25)
INSERT INTO COLLEGE_DATA VALUES(3,'NEHA',24)
INSERT INTO COLLEGE_DATA VALUES(4,'RAM',29)
INSERT INTO COLLEGE_DATA VALUES(5,'DIVYA',21)
INSERT INTO COLLEGE_DATA VALUES(6,'SAM',32)

INSERT INTO WORKING_DATA VALUES(21,'KIRAN',30)
INSERT INTO WORKING_DATA VALUES(22,'REKHA',24)
INSERT INTO WORKING_DATA VALUES(3,'HEMA',28)
INSERT INTO WORKING_DATA VALUES(24,'DEVA',20)
INSERT INTO WORKING_DATA VALUES(5,'PREM',33)
INSERT INTO WORKING_DATA VALUES(26,'STIVE',45)

/*INNER JOIN*/

SELECT * FROM COLLEGE_DATA INNER JOIN WORKING_DATA ON COLLEGE_DATA.STDID=WORKING_DATA.EMPID

/*OUTER JOIN*/
 LEFT_OUTER_JOIN:
 SELECT * FROM COLLEGE_DATA LEFT OUTER JOIN WORKING_DATA ON COLLEGE_DATA.STDID=WORKING_DATA.EMPID

 RIGHT_OUTER_JOIN:
 SELECT * FROM COLLEGE_DATA RIGHT OUTER JOIN WORKING_DATA ON COLLEGE_DATA.STDID=WORKING_DATA.EMPID

 FULL_OUTER_JOIN:
 SELECT * FROM COLLEGE_DATA FULL OUTER JOIN WORKING_DATA ON COLLEGE_DATA.STDID=WORKING_DATA.EMPID

 CROSS_JOIN:
 SELECT * FROM COLLEGE_DATA CROSS JOIN WORKING_DATA

 /*NON-ANSI JOINS*/

 EQUI_JOIN:
 SELECT * FROM COLLEGE_DATA,WORKING_DATA WHERE COLLEGE_DATA.STDID= WORKING_DATA.EMPID

 NON_EQUI_JOIN:
 SELECT * FROM COLLEGE_DATA,WORKING_DATA WHERE COLLEGE_DATA.STDID > WORKING_DATA.EMPID

