/*primary key and forgein key*/

USE VTCLASS1

CREATE TABLE EMP_JOB_DETAILS (
		EMPID INT PRIMARY KEY,
		EMPNAME CHAR(10),
		EMPSALARY MONEY
);

CREATE TABLE EMP_PER_DETAILS (
		LOC CHAR(10),
		COUNTRY CHAR(10),
		EMI MONEY,
		EMPID INT FOREIGN KEY REFERENCES EMP_JOB_DETAILS(EMPID) ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT * FROM EMP_JOB_DETAILS  /*PARENT TABLE*/
SELECT * FROM EMP_PER_DETAILS  /*CHILD TABLE*/

INSERT INTO EMP_JOB_DETAILS VALUES(1, 'SMITH', 1200)
INSERT INTO EMP_JOB_DETAILS VALUES(2, 'JOHN', 1500)
INSERT INTO EMP_JOB_DETAILS VALUES(3, 'NEHA', 1800)
INSERT INTO EMP_JOB_DETAILS VALUES(4, 'SAM', 3000)
INSERT INTO EMP_JOB_DETAILS VALUES(5, 'TINA', 4500)

INSERT INTO EMP_PER_DETAILS VALUES ('NEWYORK', 'USA', 120, 1)
INSERT INTO EMP_PER_DETAILS VALUES ('DELLAS', 'USA', 140, 2)
INSERT INTO EMP_PER_DETAILS VALUES ('LANDON', 'UK', 180, 3)
INSERT INTO EMP_PER_DETAILS VALUES ('DELHI', 'INDIA', 220, 4)
INSERT INTO EMP_PER_DETAILS VALUES ('PUNE', 'INDIA', 330, 5)

INSERT:

INSERT INTO EMP_JOB_DETAILS VALUES (6, 'NIK', 3600)
INSERT INTO EMP_PER_DETAILS VALUES('KARAD', 'INDIA',450,6)
INSERT INTO EMP_PER_DETAILS VALUES('KARAD', 'INDIA',450,9) /*NOT MATCHING REFERNCE*/

/*UPDATE*/
UPDATE EMP_JOB_DETAILS SET EMPSALARY=1700 WHERE EMPNAME='SMITH'
UPDATE EMP_JOB_DETAILS SET EMPNAME='RAM' WHERE EMPID=6
UPDATE EMP_JOB_DETAILS SET EMPID=60 WHERE EMPID=6  /*GETTING ERROR CANT UPDATE REFERENCE TABLE*/

UPDATE EMP_PER_DETAILS SET LOC='AGRA' WHERE LOC='KARAD'
UPDATE EMP_PER_DETAILS SET EMPID=2 WHERE EMPID=4

/*DELETE*/

DELETE EMP_JOB_DETAILS WHERE EMPID=3 /*POSSIBLE  ONLY WHEN THE USE CASCADE*/
DELETE EMP_PER_DETAILS WHERE EMPID=2


DROP TABLE EMP_JOB_DETAILS
DROP TABLE EMP_PER_DETAILS