USE VTCLASS1

CREATE TABLE STUDENT (STDID INT, STDNAME CHAR(10),STDAGE TINYINT)

INSERT INTO STUDENT VALUES (1, 'SMITH',23)
INSERT INTO STUDENT VALUES (2, 'JOHN',27)
INSERT INTO STUDENT VALUES (3, 'REHA',32)
INSERT INTO STUDENT VALUES (4, 'SAM',25)

SELECT * FROM STUDENT

ROLLBACK

TRUNCATE TABLE STUDENT

/*BEGIN*/

BEGIN TRANSACTION
INSERT INTO STUDENT VALUES(1,'SRINU',22)
COMMIT     /*FIX*/

/*UNDO THE OPERATION USING TCLOPERATION*/
BEGIN TRANSACTION
ROLLBACK

/*UPDATE*/
BEGIN TRANSACTION
UPDATE STUDENT SET STDAGE=34 WHERE STDID=1

/*---EXAMPLE---*/
BEGIN TRANSACTION
INSERT INTO STUDENT VALUES(1,'SRINU',22)
COMMIT     /*FIX*/

/*UNDO THE OPERATION USING TCLOPERATION*/
BEGIN TRANSACTION
ROLLBACK

/*UPDATE*/
BEGIN TRANSACTION
UPDATE STUDENT SET STDAGE=34 WHERE STDID=1
COMMIT

BEGIN TRANSACTION
UPDATE STUDENT SET STDNAME='KIRAN' WHERE STDID=1

BEGIN TRANSACTION
UPDATE STUDENT SET STDID=10 WHERE STDNAME='KIRAN'

/*UNDO THE OPERATION USING TCLOPERATION*/
BEGIN TRANSACTION
ROLLBACK

SELECT * FROM STUDENT